name: list_event
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

publish_to: 'none'

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  provider: ^6.1.1
  events:
    path: ../../data/events

  shared:
    path: ../../shared
  flutter:
    sdk: flutter



dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
